[template_archival]
    autoprune = yes
    autosnap = no
    daily = 30
    monthly = 12
    yearly = 1

[backups/pbs]
    autoprune = yes
    autosnap = no
    daily = 7
    monthly = 2
    yearly = 0
    recursive = no

[backups/sink]
    use_template = archival
    recursive = yes

[backups/tank]
    use_template = archival
    recursive = yes

[backups/offsite-homeassistant]
    use_template = archival
    recursive = yes