---
- name: Apply destination-side configuration
  when: shutdown_tracker_destination | bool
  ansible.builtin.include_tasks:
    file: destination.yaml

- name: Apply source-side configuration
  when: shutdown_tracker_source | bool
  ansible.builtin.include_tasks:
    file: source.yaml
