## Inputs:
##   - __kernel_parameters_existing_parameters_string
##   - kernel_parameters_new_parameters
## Output fact: __kernel_parameters_updated_parameters_string

# https://stackoverflow.com/questions/993452/splitting-proc-cmdline-arguments-with-spaces
- name: Set __kernel_parameters_existing_parameters_lines_result # noqa risky-shell-pipe
  ansible.builtin.shell:
    cmd: "echo {{ __kernel_parameters_existing_parameters_string | quote }} | xargs --max-args=1"
  changed_when: false
  register: __kernel_parameters_existing_parameters_lines_result
- name: Set __kernel_parameters_existing_kv_list
  ansible.builtin.set_fact:
    __kernel_parameters_existing_kv_list: "{{ __kernel_parameters_existing_parameters_lines_result.stdout_lines | map('community.general.jc', 'kv', 'raw=true') | map('dict2items') | flatten }}"
- name: Set __kernel_parameters_existing_parameters_dict_with_value_list
  ansible.builtin.set_fact:
    __kernel_parameters_existing_parameters_dict_with_value_list: "{{ __kernel_parameters_existing_parameters_dict_with_value_list | default({}) | ansible.builtin.combine({parameter_kv.key: [parameter_kv.value]}, list_merge='append') }}"
  loop: "{{ __kernel_parameters_existing_kv_list }}"
  loop_control:
    loop_var: parameter_kv
# - name: debug
#   ansible.builtin.debug:
#     var: __kernel_parameters_existing_parameters_dict_with_value_list
- name: Set __kernel_parameters_new_parameters_dict_with_value_list
  ansible.builtin.set_fact:
    __kernel_parameters_new_parameters_dict_with_value_list: "{{ __kernel_parameters_new_parameters_dict_with_value_list | default({}) | ansible.builtin.combine({parameter_kv.key: [parameter_kv.value] | flatten}, list_merge='append') }}"
  loop: "{{ kernel_parameters_new_parameters | dict2items }}"
  loop_control:
    loop_var: parameter_kv
# - name: debug
#   ansible.builtin.debug:
#     var: __kernel_parameters_new_parameters_dict_with_value_list
- name: Set __kernel_parameters_updated_parameters_dict_with_value_list for template
  ansible.builtin.set_fact:
    __kernel_parameters_updated_parameters_dict_with_value_list: "{{ __kernel_parameters_existing_parameters_dict_with_value_list | combine(__kernel_parameters_new_parameters_dict_with_value_list) }}"
# - name: debug
#   ansible.builtin.debug:
#     var: __kernel_parameters_updated_parameters_dict_with_value_list
- name: Set __kernel_parameters_updated_parameters_string
  ansible.builtin.set_fact:
    __kernel_parameters_updated_parameters_string: "{{ lookup('ansible.builtin.template', 'kernel_parameters_string.j2') }}"
# - name: debug
#   ansible.builtin.debug:
#     var: __kernel_parameters_updated_parameters_string
