## Inputs:
##   - __kernel_parameters_existing_parameters_string
##   - kernel_parameters_new_parameters
## Output fact: __kernel_parameters_updated_parameters_string

# https://stackoverflow.com/questions/993452/splitting-proc-cmdline-arguments-with-spaces
- name: Set __kernel_parameters_existing_parameters_lines_result # noqa risky-shell-pipe
  ansible.builtin.shell:
    cmd: "echo {{ __kernel_parameters_existing_parameters_string | quote }} | xargs --max-args=1"
  changed_when: false
  register: __kernel_parameters_existing_parameters_lines_result
- name: Set __kernel_parameters_updated_parameters_string
  vars:
    kernel_parameters_existing_parameters: "{{ __kernel_parameters_existing_parameters_lines_result.stdout_lines | map('community.general.jc', 'kv', 'raw=true') }}"
    kernel_parameters_updated_parameters: "{{ kernel_parameters_existing_parameters | combine(kernel_parameters_new_parameters) }}"
  ansible.builtin.set_fact:
    __kernel_parameters_updated_parameters_string: "{{ lookup('ansible.builtin.template', 'kernel_parameters_string.j2') }}"
# - name: debug
#   ansible.builtin.debug:
#     var: __kernel_parameters_updated_parameters_string
