---
- name: Set existing file path
  ansible.builtin.set_fact:
    item_src_path: "{{ (tailscale_cert_dir, item) | path_join }}"
    item_dest_path: "{{ (kvmd_ssl_dir, item) | path_join }}"
- name: Get existing file stat
  ansible.builtin.stat:
    path: "{{ item_dest_path }}"
  register: item_file_stat_result
- name: Remove existing file
  when: item_file_stat_result.stat.exists and
        item_file_stat_result.stat.lnk_source != item_src_path
  ansible.builtin.file:
    dest: "{{ item_dest_path }}"
    state: absent
- name: Symlink file
  ansible.builtin.file:
    src: "{{ item_src_path }}"
    dest: "{{ item_dest_path }}"
    state: link
