---
- name: Get tailscale domain
  ansible.builtin.command:
    cmd: tailscale cert
  register: tailscale_cert_domain_result
  changed_when: false
  failed_when: false
- name: Create tailscale certs directory
  ansible.builtin.command:
    cmd: kvmd-pstrun -- mkdir -p {{ tailscale_cert_dir }}
  changed_when: false
- name: Set pikvm_tailscale_cert_command fact
  vars:
    tailscale_domain_regex: For domain, use \"(.+)\"
    tailscale_domain: "{{ tailscale_cert_domain_result.stderr | regex_search(tailscale_domain_regex, '\\1', multiline=true) | first }}"
  ansible.builtin.set_fact:
    pikvm_tailscale_cert_command: kvmd-pstrun -- tailscale cert --cert-file {{ (tailscale_cert_dir, 'server.crt') | path_join }} --key-file {{ (tailscale_cert_dir, 'server.key') | path_join }} {{ tailscale_domain }}
- name: Create tailscale cert
  ansible.builtin.command:
    cmd: "{{ pikvm_tailscale_cert_command }}" # noqa yaml[line-length]
  changed_when: false
- name: Link SSL cert and key
  ansible.builtin.include_tasks:
    file: link_ssl_file.yaml
  loop:
    - server.crt
    - server.key
- name: Restart kvmd-nginx
  ansible.builtin.systemd:
    name: kvmd-nginx
    state: restarted
- name: Copy tailscale-cert.service
  ansible.builtin.template:
    src: templates/tailscale-cert.service.j2
    dest: /etc/systemd/system/tailscale-cert.service
    mode: "0644"
- name: Copy tailscale-cert.timer
  ansible.builtin.template:
    src: templates/tailscale-cert.timer.j2
    dest: /etc/systemd/system/tailscale-cert.timer
    mode: "0644"
- name: Enable and start tailscale-cert.service
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: "tailscale-cert.service"
    state: started
    enabled: true
- name: Enable and start tailscale-cert.timer
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: "tailscale-cert.timer"
    state: started
    enabled: true
