services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    # ports:
    #   - 8090:8090
    networks:
      - traefik
    volumes:
      - ${DOCKER_DATA_DIRECTORY}/beszel_data:/beszel_data
    labels:
      - traefik.enable=true

networks:
  traefik:
    name: traefik
    external: true