services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    # ports:
    #   - 8090:8090
    networks:
      - traefik
    volumes:
      - ${DOCKER_DATA_DIRECTORY}/beszel_data:/beszel_data
    labels:
      - traefik.enable=true
      - traefik.http.routers.beszel.rule=Host(`beszel.$DOMAIN_NAME`)
      - traefik.http.routers.beszel.service=beszel
      - traefik.http.routers.beszel-tailscale.rule=Host(`beszel.ts.$DOMAIN_NAME`)
      - traefik.http.routers.beszel-tailscale.service=beszel
      - traefik.http.services.beszel.loadbalancer.server.port=8090

networks:
  traefik:
    name: traefik
    external: true