---
services:
  nextcloud:
    image: nextcloud:${NEXTCLOUD_IMAGE_TAG}
    container_name: nextcloud
    restart: unless-stopped
    links:
      - nextcloud-mariadb
      - nextcloud-redis
    volumes:
      - ${NEXTCLOUD_DATA_DIRECTORY}:/var/www/html
    environment:
      - TRUSTED_PROXIES=${NEXTCLOUD_TRUSTED_PROXIES}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}
      - MYSQL_DATABASE=${NEXTCLOUD_MYSQL_DATABASE}
      - MYSQL_USER=${NEXTCLOUD_MYSQL_USER}
      - MYSQL_HOST=nextcloud-mariadb
      - REDIS_HOST=nextcloud-redis
    networks:
      - traefik
      - nextcloud
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.rule=Host(`nextcloud.$DOMAIN_NAME`)
      - traefik.http.routers.nextcloud.entrypoints=websecure
      - traefik.http.routers.nextcloud.tls.certresolver=cloudflare
      - traefik.http.services.nextcloud.loadbalancer.server.port=80
      - traefik.http.middlewares.nextcloud_sts.headers.stsincludesubdomains=true
      - traefik.http.middlewares.nextcloud_sts.headers.stspreload=true
      - traefik.http.middlewares.nextcloud_sts.headers.stsseconds=31536000
      - traefik.http.middlewares.nextcloud_well_known.redirectregex.permanent=true
      - "traefik.http.middlewares.nextcloud_well_known.redirectregex.regex=https://(.*)/.well-known/(?:card|cal)dav"
      - "traefik.http.middlewares.nextcloud_well_known.redirectregex.replacement=https://$${1}/remote.php/dav"
      - traefik.http.routers.nextcloud.middlewares=nextcloud_well_known,nextcloud_sts
  nextcloud-mariadb:
    image: mariadb:10
    container_name: nextcloud-mariadb
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /mnt/tank/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}
      - MYSQL_DATABASE=${NEXTCLOUD_MYSQL_DATABASE}
      - MYSQL_USER=${NEXTCLOUD_MYSQL_USER}
    networks:
      - nextcloud
  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: unless-stopped
    volumes:
      - /mnt/tank/nextcloud/redis:/data
    networks:
      - nextcloud

networks:
  nextcloud:
    name: nextcloud
  traefik:
    name: traefik
    external: true
