---
services:
  nextcloud:
    image: nextcloud:${NEXTCLOUD_IMAGE_TAG}
    container_name: nextcloud
    restart: unless-stopped
    links:
      - nextcloud-mariadb
      - nextcloud-redis
    volumes:
      - ${NEXTCLOUD_DATA_DIRECTORY}:/var/www/html
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
      - TRUSTED_PROXIES=${NEXTCLOUD_TRUSTED_PROXIES}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}
      - MYSQL_DATABASE=${NEXTCLOUD_MYSQL_DATABASE}
      - MYSQL_USER=${NEXTCLOUD_MYSQL_USER}
      - MYSQL_HOST=nextcloud-mariadb
      - REDIS_HOST=nextcloud-redis
    networks:
      - traefik
      - nextcloud
    labels:
      - ofelia.enabled=true
      - ofelia.job-exec.nextcloud-cron.user=www-data
      - ofelia.job-exec.nextcloud-cron.schedule=@every 15m
      - ofelia.job-exec.nextcloud-cron.command=php /var/www/html/cron.php
      - ofelia.job-exec.nextcloud-cron.no-overlap=true
      - traefik.enable=true
      - traefik.http.middlewares.nextcloud_sts.headers.stsincludesubdomains=true
      - traefik.http.middlewares.nextcloud_sts.headers.stspreload=true
      - traefik.http.middlewares.nextcloud_sts.headers.stsseconds=31536000
      - traefik.http.middlewares.nextcloud_well_known.redirectregex.permanent=true
      - "traefik.http.middlewares.nextcloud_well_known.redirectregex.regex=https://(.*)/.well-known/(?:card|cal)dav/"
      - "traefik.http.middlewares.nextcloud_well_known.redirectregex.replacement=https://$${1}/remote.php/dav/"
      - traefik.http.routers.nextcloud.middlewares=nextcloud_well_known,nextcloud_sts
  nextcloud-mariadb:
    image: mariadb:10
    container_name: nextcloud-mariadb
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - ${NEXTCLOUD_DATA_DIRECTORY}/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}
      - MYSQL_DATABASE=${NEXTCLOUD_MYSQL_DATABASE}
      - MYSQL_USER=${NEXTCLOUD_MYSQL_USER}
      - MARIADB_AUTO_UPGRADE=1
    networks:
      - nextcloud
  nextcloud-ofelia:
    image: mcuadros/ofelia:latest
    container_name: nextcloud-ofelia
    depends_on:
      - nextcloud
    command: daemon --docker --docker-filter label=com.docker.compose.project=${COMPOSE_PROJECT_NAME}
    networks:
      - nextcloud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: unless-stopped
    volumes:
      - ${NEXTCLOUD_DATA_DIRECTORY}/redis:/data
    networks:
      - nextcloud

networks:
  nextcloud:
    name: nextcloud
  traefik:
    name: traefik
    external: true
