---
- name: Install nut-client
  ansible.builtin.package:
    name: nut-client
- name: Copy nut.conf
  ansible.builtin.template:
    src: templates/nut_client.conf.j2
    dest: /etc/nut/nut.conf
    mode: "0640"
    owner: root
    group: "{{ nut_services_group }}"
  notify: Restart nut-client
- name: Copy upsmon.conf
  ansible.builtin.template:
    src: templates/upsmon_client.conf.j2
    dest: /etc/nut/upsmon.conf
    mode: "0640"
    owner: root
    group: "{{ nut_services_group }}"
  notify: Restart nut-client
