services:
  shinobi:
    image: registry.gitlab.com/shinobi-systems/shinobi:dev
    container_name: shinobi
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    # ports:
    #   - "8080:8080"
    environment:
      - HOME=/home/Shinobi
      - DB_HOST=shinobi-db
      - DB_USER=${SHINOBI_DB_USERNAME}
      - DB_PASSWORD=${SHINOBI_DB_PASSWORD}
      - DB_DATABASE=${SHINOBI_DB_NAME}
      - SHINOBI_UPDATE=false
    networks:
      - shinobi
      - traefik
    volumes:
      - /dev/shm/shinobi_streams:/dev/shm/streams
      - ${SHINOBI_DATA_DIRECTORY}:/home/Shinobi
    labels:
      - traefik.enable
  shinobi-db:
    image: mysql:5.7
    container_name: shinobi-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${SHINOBI_DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${SHINOBI_DB_NAME}
      - MYSQL_USER=${SHINOBI_DB_USERNAME}
      - MYSQL_PASSWORD=${SHINOBI_DB_PASSWORD}
    networks:
      - shinobi
    volumes:
      - ${SHINOBI_DB_DIRECTORY}:/var/lib/mysql
      # - ./mysql-init:/docker-entrypoint-initdb.d

networks:
  shinobi:
    name: shinobi
  traefik:
    name: traefik
    external: true
