---
services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PASSWORD= #optional
      - CLI_ARGS= #optional
    networks:
      - traefik
    volumes:
      - ${DOCKER_DATA_DIRECTORY}/calibre:/config
      # - /dev/dri:/dev/dri
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.calibre-gui.rule=Host(`calibre-gui.$DOMAIN_NAME`)
      - traefik.http.routers.calibre-gui.service=calibre-gui
      - traefik.http.services.calibre-gui.loadbalancer.server.port=8080
      - traefik.http.routers.calibre.rule=Host(`calibre.$DOMAIN_NAME`)
      - traefik.http.routers.calibre.service=calibre
      - traefik.http.services.calibre.loadbalancer.server.port=8081
  jellystat:
    image: cyfershepard/jellystat:latest
    container_name: jellystat
    depends_on:
      - jellystat-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${JELLYSTAT_DB_USERNAME}
      POSTGRES_PASSWORD: ${JELLYSTAT_DB_PASSWORD}
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      JWT_SECRET: ${JELLYSTAT_JWT_SECRET}
      TZ: ${TZ}
    networks:
      - traefik
      - jellystat
    volumes:
      - ${DOCKER_DATA_DIRECTORY}/jellystat:/app/backend/backup-data # Mounting the volume
    labels:
      - traefik.enable=true
  jellystat-db:
    image: postgres:15
    container_name: jellystat-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${JELLYSTAT_DB_USERNAME}
      POSTGRES_PASSWORD: ${JELLYSTAT_DB_PASSWORD}
    networks:
      - jellystat
    volumes:
      - ${DOCKER_DATA_DIRECTORY}/jellystat-db:/var/lib/postgresql/data
  tautulli:
    image: tautulli/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - traefik
    volumes:
      - ${DOCKER_DATA_DIRECTORY}/tautulli/config:/config
    labels:
      - traefik.enable=true
  trakt-for-appletv:
    image: forgejo.omegaho.me/andy/trakt-for-appletv:latest
    container_name: trakt-for-appletv
    network_mode: host
    volumes:
      - ${DOCKER_DATA_DIRECTORY}/trakt-for-appletv/data:/opt/TVRemote/data

networks:
  jellystat:
    name: jellystat
  traefik:
    name: traefik
    external: true
