services:
  octoprint:
    image: octoprint/octoprint:latest
    container_name: octoprint
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    networks:
      - traefik
    volumes:
      - ${DOCKER_DATA_DIRECTORY}/octoprint:/octoprint
    labels:
      - traefik.enable=true
  spoolman:
    image: ghcr.io/donkie/spoolman:latest
    container_name: spoolman
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    networks:
      - traefik
    volumes:
      - ${DOCKER_DATA_DIRECTORY}/spoolman:/home/app/.local/share/spoolman
    # ports:
    #   # Map the host machine's port 7912 to the container's port 8000
    #   - "7912:8000"
    labels:
      - traefik.enable=true

networks:
  traefik:
    name: traefik
    external: true