---
services:
  wallos:
    container_name: wallos
    image: bellamy/wallos:latest
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    networks:
      - traefik
    volumes:
      - ${DOCKER_DATA_DIRECTORY}/wallos/db:/var/www/html/db
      - ${DOCKER_DATA_DIRECTORY}/wallos/logos:/var/www/html/images/uploads/logos
    labels:
      - traefik.enable=true
networks:
  traefik:
    name: traefik
    external: true