---
services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    user: ${PUID}:${PGID}
    environment:
     - GF_SERVER_ROOT_URL=https://grafana.$DOMAIN_NAME
    networks:
      - traefik
    volumes:
      - ${DOCKER_DATA_DIRECTORY}/grafana:/var/lib/grafana
    labels:
      - traefik.enable=true
  healthchecks:
    image: lscr.io/linuxserver/healthchecks:latest
    container_name: healthchecks
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SITE_ROOT=https://healthchecks.${DOMAIN_NAME}
      - SITE_NAME=Healthchecks
      - DEFAULT_FROM_EMAIL=healthchecks@${DOMAIN_NAME}
      - EMAIL_HOST=${HEALTHCHECKS_EMAIL_HOST}
      - EMAIL_PORT=${HEALTHCHECKS_EMAIL_PORT}
      - EMAIL_HOST_USER=${HEALTHCHECKS_EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${HEALTHCHECKS_EMAIL_HOST_PASSWORD}
      - EMAIL_USE_TLS=${HEALTHCHECKS_EMAIL_USE_TLS}
      - SUPERUSER_EMAIL=${HEALTHCHECKS_SUPERUSER_EMAIL}
      - SUPERUSER_PASSWORD=${HEALTHCHECKS_SUPERUSER_PASSWORD}
      - REGENERATE_SETTINGS=True #optional
      - APPRISE_ENABLED=False #optional
      - PUSHOVER_API_TOKEN=${HEALTHCHECKS_PUSHOVER_API_TOKEN}
      - PUSHOVER_SUBSCRIPTION_URL=${HEALTHCHECKS_PUSHOVER_SUBSCRIPTION_URL}
      - DEBUG=False
    networks:
      - traefik
    volumes:
      - ${DOCKER_DATA_DIRECTORY}/healthchecks:/config
    labels:
      - traefik.enable=true
  influxdb2:
    image: influxdb:2
    container_name: influxdb2
    restart: unless-stopped
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_INIT_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_INIT_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_INIT_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_INIT_BUCKET}
    volumes:
      - ${DOCKER_DATA_DIRECTORY}/influxdb2/data:/var/lib/influxdb2
      - ${DOCKER_DATA_DIRECTORY}/influxdb2/config:/etc/influxdb2
  prometheus:
    image: quay.io/prometheus/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    user: ${PUID}:${PGID}
    networks:
      - traefik
    volumes:
      - ${DOCKER_DATA_DIRECTORY}/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${DOCKER_DATA_DIRECTORY}/prometheus/data:/prometheus
    labels:
      - traefik.enable=true
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - ${DOCKER_DATA_DIRECTORY}/uptime-kuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true

networks:
  traefik:
    name: traefik
    external: true
