- name: Install beszel-agent
  ansible.builtin.include_role:
    name: github_release_install
  vars:
    github_release_install_repo: henrygd/beszel
    github_release_install_asset_patterns:
      x86_64: "beszel-agent_linux_amd64.tar.gz"
      aarch64: "beszel-agent_linux_arm64.tar.gz"
      armv7l: "beszel-agent_linux_arm.tar.gz"
    github_release_install_archive_type: tarball
    github_release_install_binary_in_archive: beszel-agent
    github_release_install_binary_path: "{{ beszel_agent_bin_path }}"
    github_release_install_version_command: "{{ beszel_agent_bin_path }} -v"
