- name: Set beszel_agent_asset_name - Linux x86_64
  when: ansible_system == 'Linux' and ansible_architecture == 'x86_64'
  ansible.builtin.set_fact:
    beszel_agent_asset_name: beszel-agent_linux_amd64.tar.gz
- name: Set beszel_agent_asset_name - Linux aarch64
  when: ansible_system == 'Linux' and ansible_architecture == 'aarch64'
  ansible.builtin.set_fact:
    beszel_agent_asset_name: beszel-agent_linux_arm64.tar.gz
- name: Set beszel_agent_asset_name - Linux armv7l
  when: ansible_system == 'Linux' and ansible_architecture == 'armv7l'
  ansible.builtin.set_fact:
    beszel_agent_asset_name: beszel-beszel-agent_linux_arm.tar.gz
- name: Set beszel_agent_asset_name - Darwin x86_64
  when: ansible_system == 'Darwin' and ansible_architecture == 'x86_64'
  ansible.builtin.set_fact:
    beszel_agent_asset_name: beszel-agent_darwin_amd64.tar.gz
- name: Set beszel_agent_asset_name - Darwin aarch64
  when: ansible_system == 'Darwin' and ansible_architecture == 'aarch64'
  ansible.builtin.set_fact:
    beszel_agent_asset_name: beszel-agent_darwin_arm64.tar.gz
- name: Get latest release from GitHub
  ansible.builtin.uri:
    url: https://api.github.com/repos/henrygd/beszel/releases/latest
    return_content: true
  register:
    beszel_latest_release_json_response
- name: Download binary # noqa jinja[invalid]
  vars:
    browser_download_url_json_query: "assets[?name == '{{ beszel_agent_asset_name }}'].browser_download_url"
    browser_download_urls: "{{ beszel_latest_release_json_response.json | json_query(browser_download_url_json_query) }}"
    beszel_asset_url: "{{ browser_download_urls | first }}"
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ beszel_asset_url }}"
    dest: "{{ beszel_agent_bin_path }}"
    mode: "0755"
    owner: root
  register: beszel_download_unarchive_result
