---
- name: Configure client
  when: remote_power_control_client
  ansible.builtin.include_tasks:
    file: "client.yaml"
- name: Configure target
  when: remote_power_control_target
  ansible.builtin.include_tasks:
    file: "target.yaml"
