---
- name: "Run {{ docker_compose_base_command }} up" # noqa name[template]
  become: false
  ansible.builtin.command:
    cmd: "{{ docker_compose_base_command }}"
  register: docker_compose_up_result
  changed_when: docker_compose_up_result.stderr_lines | reject('match', '.*(Running).*') is any
