---
- name: "Run {{ docker_compose_up_command }}"
  become: false
  ansible.builtin.command:
    cmd: "{{ docker_compose_up_command }}"
  register: docker_compose_up_result
  changed_when: docker_compose_up_result.stderr_lines | select('match', ' Container.*') | reject('match', '.*(Running).*') is any
