---
- name: Set ansible_non_become_user facts
  when: docker_compose_uid is not defined and docker_compose_gid is not defined
  ansible.builtin.include_role:
    name: ansible_non_become_user_facts
- name: Create docker compose directory
  ansible.builtin.file:
    path: "{{ docker_compose_dst_directory_path }}"
    state: directory
    owner: "{{ docker_compose_uid }}"
    group: "{{ docker_compose_gid }}"
    mode: "0755"
- name: "Copy {{ docker_compose_src_file_path }}"
  ansible.builtin.template:
    src: "{{ docker_compose_src_file_path }}"
    dest: "{{ docker_compose_dst_file_path }}"
    owner: "{{ docker_compose_uid }}"
    group: "{{ docker_compose_gid }}"
    mode: "0644"
- name: Copy docker_compose_directory_files
  ansible.builtin.template:
    src: "{{ docker_compose_directory_file }}"
    dest: "{{ (docker_compose_dst_directory_path, docker_compose_directory_file | basename) | path_join }}"
    owner: "{{ docker_compose_uid }}"
    group: "{{ docker_compose_gid }}"
    mode: "0644"
  loop: "{{ docker_compose_directory_files | default([]) }}"
  loop_control:
    loop_var: docker_compose_directory_file
- name: Copy env file
  ansible.builtin.include_tasks:
    file: copy_env.yaml
- name: Copy main docker compose file
  when: docker_compose_should_include_in_main_compose_file
  ansible.builtin.include_tasks:
    file: copy_main_docker_compose.yaml
- name: Copy config files
  when: docker_compose_src_config_files | default([]) | length > 0
  ansible.builtin.include_tasks:
    file: copy_config_files.yaml
- name: Copy scripts
  when: docker_compose_copy_scripts
  ansible.builtin.copy:
    src: "{{ script }}"
    dest: "/usr/local/bin"
    mode: "0755"
  loop:
    - files/dc
    - files/dcup
  loop_control:
    loop_var: script
- name: Run docker compose pull
  ansible.builtin.include_tasks:
    file: "docker_compose_pull.yaml"
- name: Run docker compose up
  when: docker_compose_should_run_up
  ansible.builtin.include_tasks:
    file: "docker_compose_up.yaml"
- name: Run docker system prune
  when: docker_compose_should_prune
  ansible.builtin.include_tasks:
    file: "docker_system_prune.yaml"
