---
- name: "Check if {{ docker_compose_service_name }} is running" # noqa name[template]
  ansible.builtin.command:
    cmd: "docker ps --filter 'name={{ docker_compose_service_name }}' {% raw %}--format='{{json .}}'{% endraw %}"
  register: docker_service_running_result
  changed_when: false
- name: "Restart {{ docker_compose_service_name }}"
  when: docker_service_running_result.stdout | length > 0
  ansible.builtin.command:
    cmd: "docker restart {{ docker_compose_service_name }}"
  changed_when: false
  listen: docker_compose_restart_service
