---
- name: Set facts
  ansible.builtin.include_tasks:
    file: "set_facts.yaml"
- name: Run docker compose pull
  ansible.builtin.include_tasks:
    file: "docker_compose_pull.yaml"
- name: Run docker compose up
  ansible.builtin.include_tasks:
    file: "docker_compose_up.yaml"
- name: Run docker system prune
  ansible.builtin.include_tasks:
    file: "docker_system_prune.yaml"
