---
- name: Configure ipv4 forwarding
  ansible.builtin.copy:
    content: |
      net.ipv4.ip_forward = 1
      net.ipv6.conf.all.forwarding = 1
    dest: /etc/sysctl.d/99-tailscale.conf
    mode: "0644"
    owner: root
    group: root
  register: ip_forwarding_result
- name: Load sysctl file # noqa no-handler
  when: ip_forwarding_result.changed
  ansible.builtin.command:
    cmd: sysctl --load=/etc/sysctl.d/99-tailscale.conf
  changed_when: true
- name: Get subnet routes
  ansible.builtin.command:
    cmd: ip route show protocol kernel
  register: ip_routes_result
  changed_when: false
- name: Set subnet_routes fact
  vars:
    subnet_route_regex: '^([\d\.\/]+)'
  ansible.builtin.set_fact:
    subnet_routes: "{{ ip_routes_result.stdout | regex_search(subnet_route_regex, '\\1') }}"
- name: Install tailscale
  community.general.pacman:
    name: tailscale-pikvm
    update_cache: true
    state: present
- name: Enable tailscaled
  ansible.builtin.systemd:
    name: tailscaled
    enabled: true
    state: started
- name: Run tailscale up advertising exit node
  vars:
    advertise_routes: "{{ subnet_routes | join(',') }}"
  ansible.builtin.command:
    cmd: tailscale up --authkey="{{ tailscale_authkey }}" --advertise-exit-node --advertise-routes="{{ advertise_routes }}"
  changed_when: false
