---
services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION}
    container_name: immich-server
    restart: unless-stopped
    depends_on:
      - immich-redis
      - immich-database
    environment:
      - TZ=${TZ}
      - DB_DATABASE_NAME=${IMMICH_DB_DATABASE_NAME}
      - DB_HOSTNAME=immich-postgres
      - DB_PASSWORD=${IMMICH_DB_PASSWORD}
      - DB_USERNAME=${IMMICH_DB_USERNAME}
      - REDIS_HOSTNAME=immich-redis
    networks:
      - traefik
      - immich
    volumes:
      - ${IMMICH_PHOTOS_DIRECTORY}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.immich.rule=Host(`immich.$DOMAIN_NAME`)
      - dsm.name=Immich

  immich-redis:
    container_name: immich-redis
    image: redis:6.2-alpine
    restart: unless-stopped
    networks:
      - immich

  immich-database:
    container_name: immich-postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    environment:
      POSTGRES_PASSWORD: ${IMMICH_DB_PASSWORD}
      POSTGRES_USER: ${IMMICH_DB_USERNAME}
      POSTGRES_DB: ${IMMICH_DB_DATABASE_NAME}
    volumes:
      - ${IMMICH_DB_DIRECTORY}:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - immich

networks:
  immich:
    name: immich
  traefik:
    name: traefik
    external: true