---
- name: Enable SSH forwarding for sudo
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    insertafter: '^#?\s*Defaults\s+env_keep\b'
    line: 'Defaults    env_keep += "SSH_AUTH_SOCK"'
- name: Clone settings repo # noqa latest[git]
  become: false
  ansible.builtin.git:
    repo: git@github.com:andyattebery/settings.git
    accept_newhostkey: true
    dest: ~/settings
- name: Link dotfiles
  become: false
  ansible.builtin.command:
    cmd: ./link_settings.fish dotfiles applications/{{ item }}
    chdir: ~/settings
  loop: "{{ settings_repo_application_dotfiles }}"
  register: link_settings_result
  changed_when: '"already links to" not in link_settings_result.stdout'
