services:
  invoiceninja-server:
    image: nginx:1
    restart: unless-stopped
    volumes:
      # Vhost configuration
      #- ./config/caddy/Caddyfile:/etc/caddy/Caddyfiledocker-com
      - ${DOCKER_DATA_DIRECTORY}/${INVOICENINJA_NGINX_CONF_FILE_RELATIVE_PATH}:/etc/nginx/conf.d/invoiceninja_nginx_conf_file:ro
      - ${DOCKER_DATA_DIRECTORY}/invoiceninja/app/public:/var/www/app/public:ro
    depends_on:
      - invoiceninja-app
    networks:
      - invoiceninja
      - traefik
    # extra_hosts:
    #   - "in5.localhost:192.168.0.124 " #host and ip
    labels:
      - traefik.enable: true
      - traefik.http.routers.invoiceninja.rule: Host(`invoiceninja.$DOMAIN_NAME`)
  invoiceninja-app:
    image: invoiceninja/invoiceninja:5
    env_file: env
    restart: unless-stopped
    environment:
      APP_URL: http://in.localhost:8003
      APP_KEY: <insert your generated key in here>
      APP_DEBUG: true
      REQUIRE_HTTPS: false
      PHANTOMJS_PDF_GENERATION: false
      PDF_GENERATOR: snappdf
      TRUSTED_PROXIES: '*'
      QUEUE_CONNECTION: database

      # DB connection
      DB_HOST: invoiceninja-db
      DB_PORT: 3306
      DB_DATABASE: ninja
      DB_USERNAME: ninja
      DB_PASSWORD: ninja

      # Create initial user
      # Default to these values if empty
      # IN_USER_EMAIL: admin@example.com
      # IN_PASSWORD: changeme!
      IN_USER_EMAIL: ""
      IN_PASSWORD: 

      # Mail options
      MAIL_MAILER: log
      MAIL_HOST: smtp.mailtrap.io
      MAIL_PORT: 2525
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null
      MAIL_FROM_ADDRESS: 'user@example.com'
      MAIL_FROM_NAME: 'Self Hosted User'
    volumes:
      - ./config/hosts:/etc/hosts:ro
      - ./docker/app/public:/var/www/app/public:rw,delegated
      - ./docker/app/storage:/var/www/app/storage:rw,delegated
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/php/php-cli.ini:/usr/local/etc/php/php-cli.ini
    depends_on:
      - invoiceninja-db
    networks:
      - invoiceninja
    # extra_hosts:
    #   - "in5.localhost:192.168.0.124 " #host and ip

  invoiceninja-db:
    image: mysql:8
    ports:
      - "3305:3306"
    restart: unless-stopped
    env_file: env
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:rw,delegated
    networks:
      - invoiceninja
    extra_hosts:
      - "in5.localhost:192.168.0.124 " #host and ip

networks:
  invoiceninja:
  traefik:
    external: true
