---
# Configures SATA Active Link Power Management
- name: Copy power_saving_sata.rule
  when: (power_saving_sata_all_devices is defined and power_saving_sata_all_devices) or (power_saving_sata_devices is defined and power_saving_sata_devices | length > 0)
  ansible.builtin.template:
    src: templates/10-power-saving-sata.rules.j2
    dest: /etc/udev/rules.d/10-power-saving-sata.rules
    mode: "0644"
