---
- name: Install sysfsutils
  ansible.builtin.package:
    name: sysfsutils
    state: present
- name: Set PCIe ASPM policy to powersave
  ansible.builtin.copy:
    dest: /etc/sysfs.d/power_saving_pci.conf
    content: "module/pcie_aspm/parameters/policy = powersave"
    mode: "0644"
- name: Copy PCI runtime power management udev rule
  when: (power_saving_pcie_runtime_all_devices_enabled) or (power_saving_pcie_runtime_devices is defined and power_saving_pcie_runtime_devices | length > 0)
  ansible.builtin.template:
    src: templates/10-power-saving-pcie.rules.j2
    dest: /etc/udev/rules.d/10-power-saving-pcie.rules
    mode: "0644"
- name: Set PCI runtime power control to auto
  when: power_saving_pcie_runtime_all_devices_enabled
  ansible.builtin.copy:
    dest: /etc/sysfs.d/power_saving_pci.conf
    content: |
      bus/pci/devices/*/power/control = auto
      bus/pci/devices/*/ata*/power/control = auto
    mode: "0644"
