---
- name: Find interface name for MAC address
  ansible.builtin.shell:
    cmd: |
      ip -o -s link | grep {{ interface_mac_address | lower }} | awk '{ print $2 }' | tr -d ":"
  register: interface_name_result
  changed_when: false
- name: debug
  ansible.builtin.debug:
    msg: "interface_name: {{ interface_name_result.stdout }}"
- name: Add interface
  vars:
    inteface_name: "{{ interface_name_result.stdout }}"
  community.general.interfaces_file:
    iface: "{{ interface_name }}"
    state: present


