- name: Install topgrade
  ansible.builtin.include_role:
    name: github_release_install
  vars:
    github_release_install_repo: topgrade-rs/topgrade
    github_release_install_asset_patterns:
      x86_64: "_amd64.deb"
      aarch64: "_arm64.deb"
      armv7l: "_armhf.deb"
    github_release_install_archive_type: deb
    github_release_install_binary_path: "{{ topgrade_bin_path }}"
    github_release_install_version_command: "{{ topgrade_bin_path }} -V"
