---
- name: Initial scrutiny web docker compose setup
  vars:
    docker_compose_src_file_path: files/docker-compose-scrutiny-web.yaml
    docker_compose_src_config_files:
      - src_file_path: templates/scrutiny.yaml.j2
        dst_relative_file_path: scrutiny/config/scrutiny.yaml
        service_name_to_restart: scrutiny-web
  ansible.builtin.include_role:
    name: docker_compose
