services:
  cadvisor:
    image: ghcr.io/google/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    ports:
    - 8080:8080
    privileged: true
    command:
      - --docker_only=true
      - --housekeeping_interval=30s
      - --max_housekeeping_interval=60s
      - --disable_metrics=disk,diskIO,tcp,udp,advtcp,referenced_memory,resctrl,cpu_topology,memory_numa,process,hugetlb
    devices:
      - /dev/kmsg
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
