- name: Validate inputs
  ansible.builtin.assert:
    that:
      - pbs_exporter_pbs_username | length > 0
      - pbs_exporter_api_token_name | length > 0
      - pbs_exporter_api_token_path | length > 0
- name: Install
  ansible.builtin.include_tasks:
    file: install.yaml
- name: Create user
  ansible.builtin.include_tasks:
    file: user.yaml
- name: Bootstrap PBS user + token + ACL
  ansible.builtin.include_tasks:
    file: bootstrap.yaml
- name: Enable service
  ansible.builtin.include_tasks:
    file: service.yaml
