---
certbot_asrock_ipmi_cert_updater_bin_path: "{{ certbot_asrock_ipmi_cert_updater_directory_path }}/asrock_ipmi_cert_updater.py"
certbot_asrock_ipmi_cert_updater_ini_path: "{{ certbot_asrock_ipmi_cert_updater_directory_path }}/asrock_ipmi_cert_updater.ini"
certbot_asrock_ipmi_cert_updater_container_bin_path: "{{ certbot_asrock_ipmi_cert_updater_container_directory_path }}/asrock_ipmi_cert_updater.py"
certbot_asrock_ipmi_cert_updater_container_ini_path: "{{ certbot_asrock_ipmi_cert_updater_container_directory_path }}/asrock_ipmi_cert_updater.ini"
certbot_asrock_ipmi_cert_updater_container_certificates_path: "/certbot/config/live/{{ certbot_asrock_ipmi_cert_updater_domain_name }}"
