services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    shm_size: "64mb" # update for your cameras based on calculation above
    # devices:
    #   - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
    #   - /dev/apex_0:/dev/apex_0    # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
    #   - /dev/video11:/dev/video11  # For Raspberry Pi 4B
    #   - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    ports:
      # - "5000:5000" # Web UI
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    networks:
      - traefik
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_DATA_DIRECTORY}/${FRIGATE_RELATIVE_CONFIG_DIRECTORY}:/config
      - ${FRIGATE_STORAGE_DIRECTORY}:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    labels:
      - traefik.enable=true
      - traefik.http.services.frigate.loadbalancer.server.port=5000

networks:
  traefik:
    name: traefik
    external: true
