---
syncoid_command: "/usr/sbin/syncoid --no-privilege-elevation --recursive --compress lz4 --no-sync-snap --create-bookmark --sshkey {{ syncoid_ssh_key_path }}"
syncoid_source_ssh_private_key_name: id_ed25519_syncoid
