---
- name: Remove repo key from deprecated /etc/apt/trusted.gpg
  ansible.builtin.command:
    cmd: "apt-key --keyring /etc/apt/trusted.gpg del '24A6 3B31 CAB4 1B33 EC48  801E 2CE2 AC08 D880 C8E4'"
  changed_when: false
- name: Add fish apt repository key
  ansible.builtin.get_url:
    url: "https://download.opensuse.org/repositories/shells:fish:release:3/Debian_{{ ansible_distribution_major_version }}/Release.key"
    dest: /etc/apt/trusted.gpg.d/shells_fish_release_3.asc
    mode: '0644'
    force: true
- name: Add fish apt repository
  ansible.builtin.apt_repository:
    repo: "deb http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_{{ ansible_distribution_major_version }}/ /"
    filename: shells_fish_release_3.list
    state: present
    update_cache: false
- name: Install fish
  ansible.builtin.apt:
    name: fish
    update_cache: true
