---
- name: Add fish repository
  ansible.builtin.command:
    cmd: "dnf config-manager --add-repo https://download.opensuse.org/repositories/shells:fish:release:{{ fish_version }}/Fedora_{{ ansible_distribution_major_version }}/shells:fish:release:{{ fish_version }}.repo"
  changed_when: false
- name: Install fish
  ansible.builtin.dnf:
    name: fish
    state: present
    update_cache: true
