---
- name: Install on Debian
  when: ansible_distribution == 'Debian'
  ansible.builtin.include_tasks:
    file: install_debian.yaml
- name: Install on Ubuntu
  when: ansible_distribution == 'Ubuntu'
  ansible.builtin.include_tasks:
    file: install_ubuntu.yaml
- name: Get shell path
  ansible.builtin.command:
    cmd: which fish
  register: which_fish
  changed_when: false
- name: Change shell to fish
  when: fish_install_change_shell
  ansible.builtin.user:
    user: "{{ ansible_user }}"
    shell: "{{ which_fish.stdout }}"
