---
- name: Install on Debian and Ubuntu
  when: ansible_facts['distribution'] in ['Debian', 'Ubuntu']
  block:
    - name: Configure the apt source
      ansible.builtin.include_tasks: apt_repo.yaml

    - name: Install mise
      ansible.builtin.apt:
        name: mise
        update_cache: true

- name: Install on Fedora
  when: ansible_facts['distribution'] == 'Fedora'
  ansible.builtin.include_tasks:
    file: install_fedora.yaml
