---
- name: Install certbot-dns-cloudflare
  community.general.pacman:
    name:
      - certbot-dns-cloudflare
    update_cache: true
- name: Get cloudflare credentials file stat
  ansible.builtin.stat:
    path: "{{ pikvm_certbot_dns_cloudflare_credentials_path }}"
  register: pikvm_certbot_dns_cloudflare_credentials_stat_result
- name: Create cloudflare credentials file
  when: not pikvm_certbot_dns_cloudflare_credentials_stat_result.stat.exists
  ansible.builtin.command:
    cmd: "kvmd-pstrun -- {{ kvmd_pstrun_cmd }}"
  loop:
    - "mkdir -p {{ pikvm_certbot_dns_cloudflare_credentials_path | dirname }}"
    - "bash -c \"echo 'dns_cloudflare_api_token = {{ cloudflare_api_token }}' > {{ pikvm_certbot_dns_cloudflare_credentials_path }}\""
    - "chmod 600 {{ pikvm_certbot_dns_cloudflare_credentials_path }}"
    - "chown kvmd-certbot: {{ pikvm_certbot_dns_cloudflare_credentials_path }}"
  loop_control:
    loop_var: kvmd_pstrun_cmd
  register: kvmd_pstrun_result
  changed_when: true
- name: Create certificate
  ansible.builtin.command:
    cmd: >
      kvmd-certbot certonly
      --dns-cloudflare
      --dns-cloudflare-propagation-seconds 60
      --dns-cloudflare-credentials {{ pikvm_certbot_dns_cloudflare_credentials_path }}
      --agree-tos
      --noninteractive
      --email {{ certbot_email }}
      --domain {{ ansible_host }}
  register: kvmd_certbot_certonly_result
  changed_when: "'Certificate not yet due for renewal' not in kvmd_certbot_certonly_result.stdout"
- name: Install certificate for nginx
  when: "'Certificate not yet due for renewal' not in kvmd_certbot_certonly_result.stdout"
  ansible.builtin.command:
    cmd: "kvmd-certbot install_nginx {{ ansible_host }}"
  changed_when: true
- name: Enable and start kvmd-certbot.timer
  ansible.builtin.systemd_service:
    name: "kvmd-certbot.timer"
    state: started
    enabled: true
