---
- name: Copy healthchecks.service
  ansible.builtin.template:
    src: "templates/healthchecks@.service.j2"
    dest: "/etc/systemd/system/healthchecks@.service"
    mode: "0644"
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
