---
- name: Set item_src_path and item_dest_path
  ansible.builtin.set_fact:
    item_src_path: "{{ (certbot_certificate_directory_path, symlink_item.src_file) | path_join }}"
    item_dest_path: "{{ symlink_item.dest_file_path }}"
- name: Get existing file stat
  ansible.builtin.stat:
    path: "{{ item_dest_path }}"
  register: item_file_stat_result
# - ansible.builtin.debug:
#     msg: "{{ item_file_stat_result.stat }}"
- name: Remove existing file
  when: item_file_stat_result.stat.exists and
        (not item_file_stat_result.stat.islnk or
        item_file_stat_result.stat.lnk_target != item_src_path)
  ansible.builtin.file:
    dest: "{{ item_dest_path }}"
    state: absent
- name: Symlink file
  ansible.builtin.file:
    src: "{{ item_src_path }}"
    dest: "{{ item_dest_path }}"
    state: link
