keys:
  # Operator key (generate with: age-keygen)
  - &operator age1lvxpamj6qz8tl9py2qqk3lyejx60gn8zyfelrn4g628l4xl6wcfs75ceuq

creation_rules:
  - path_regex: .*
    key_groups:
      - age:
        - *operator
