keys:
  # Operator key (generate with: age-keygen)
  - &operator age1lvxpamj6qz8tl9py2qqk3lyejx60gn8zyfelrn4g628l4xl6wcfs75ceuq

  - &network-03 age1gdrk0p4cn2z0mwr8hvdqstc2tlqxd9vkek4u27gllgladd2lxassw9j2w6
  - &network-01 age1jmlzz6q57ym8sw9826mgp0d6gfxp7aetadxh2ne4mtq9tddaaa0s6j2qc2
creation_rules:
  - path_regex: .*
    key_groups:
      - age:
        - *operator
        - *network-01
        - *network-03
