---
- name: Initial docker compose setup
  vars:
    docker_compose_envs:
      - WIREGUARD_EXTERNAL_DOMAIN={{ wireguard_external_domain }}
      - WIREGUARD_PORT={{ wireguard_port }}
      - WIREGUARD_PEERS={{ wireguard_peers }}
      - WIREGUARD_INTERNAL_SUBNET={{ wireguard_internal_subnet }}
    docker_compose_src_file_path: files/docker-compose-wireguard.yaml
    docker_compose_dst_directory_name: wireguard
    docker_compose_should_run_up: true
  ansible.builtin.include_role:
    name: docker_compose
