---
scrutiny_collector_name: "{{ ansible_hostname }}"
scrutiny_dir: /opt/scrutiny
scrutiny_bin_dir: "{{ (scrutiny_dir, 'bin') | path_join }}"
scrutiny_config_dir: "{{ (scrutiny_dir, 'config') | path_join }}"
scrutiny_collector_run_command: "{{ (scrutiny_bin_dir, scrutiny_collector_bin_name) | path_join }} run --config {{ scrutiny_config_dir }}"
scrutiny_collector_systemd_after: network-online.target
scrutiny_collector_systemd_requires: network-online.target
scrutiny_collector_timer_on_calendar: "*-*-* 0:00:00"
