---
- name: Set docker_compose_dst_directory_path
  ansible.builtin.import_role:
    name: docker_compose
    tasks_from: set_facts
- name: Clone omnivore repo # noqa latest[git]
  ansible.builtin.git:
    repo: "https://github.com/omnivore-app/omnivore.git"
    dest: "{{ docker_compose_omnivore_repo_path }}"
- name: Configure omnivore docker compose
  vars:
    docker_compose_src_file_path: files/docker-compose-omnivore.yaml
    docker_compose_envs:
      POSTGRES_USER: "{{ omnivore_postgres_user }}"
      POSTGRES_PASSWORD: "{{ omnivore_postgres_password }}"
      POSTGRES_DB: "{{ omnivore_postgres_db }}"
      MINIO_USERNAME: "{{ minio_username }}"
      MINIO_PASSWORD: "{{ minio_password }}"
  ansible.builtin.include_role:
    name: docker_compose
