---
- name: Add udev rule to use r8125 module for specific devices
  ansible.builtin.template:
    src: templates/99-r8169-to-r8125.rules.j2
    dest: /etc/udev/rules.d/99-r8169-to-r8125.rules
    owner: root
    group: root
    mode: "0644"
