---
- name: Install packages
  ansible.builtin.apt:
    name:
      - zfsutils-linux
- name: Configure zed notifications
  ansible.builtin.include_role:
    name: zed_notifications
- name: Configure syncoid destination
  ansible.builtin.include_role:
    name: syncoid_destination
- name: Configure scrutiny collector
  ansible.builtin.include_role:
    name: scrutiny_collector
