---
- name: Add udev rule to use r8152 module for specific devices
  ansible.builtin.template:
    src: templates/99-cdc_ncm-to-r8152.rules.j2
    dest: /etc/udev/rules.d/99-cdc_ncm-to-r8152.rules
    owner: root
    group: root
    mode: "0644"
