---
- name: Get efibootmgr
  ansible.builtin.command:
    cmd: efibootmgr -v
  register:
    efibootmgr_result
  changed_when: false
- name: Configure grub
  when: "'grubx64.efi' in efibootmgr_result.stdout | lower"
  block:
    - name: Update /etc/default/grub
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: ^GRUB_CMDLINE_LINUX_DEFAULT
        line: GRUB_CMDLINE_LINUX_DEFAULT="{{ kernel_cmdline_parameters }}"
      register: update_grub_cmdline_result
    - name: Update grub # noqa no-handler
      when: update_grub_cmdline_result.changed
      ansible.builtin.command:
        cmd: update-grub
      changed_when: true
- name: Configure systemd-boot
  when: "'bootx64.efi' in efibootmgr_result.stdout | lower"
  block:
    - name: Update /etc/kernel/cmdline
      ansible.builtin.copy:
        dest: /etc/kernel/cmdline
        mode: "0644"
        content: "{{ kernel_cmdline_parameters }}"
      register: update_kernel_cmdline_result
    - name: Run proxmox-boot-tool refresh  # noqa no-handler
      when: update_kernel_cmdline_result.changed
      ansible.builtin.command:
        cmd: proxmox-boot-tool refresh
      changed_when: true
