---
dependencies: []

galaxy_info:
  role_name: realtek_r8125_dkms_package
  author: andyattebery
  description: Install r8125 DKMS via the Debian r8125-dkms package and swap from kernel r8169 driver
  license: "license (BSD, MIT)"
  min_ansible_version: "2.4"
  platforms:
    - name: Debian
      versions:
        - all
