---
- name: Remove repo key from deprecated /etc/apt/trusted.gpg
  ansible.builtin.command:
    cmd: "apt-key --keyring /etc/apt/trusted.gpg del '2A65 8CFA 6380 FA92 EAE4  A854 248B F908 2524 EEFD'"
  changed_when: false
- name: Add fish apt repository key
  ansible.builtin.get_url:
    url: "https://download.opensuse.org/repositories/filesystems:/snapper/Debian_{{ ansible_distribution_major_version }}/Release.key"
    dest: /etc/apt/trusted.gpg.d/filesystems_snapper.asc
    mode: '0644'
    force: true
- name: Add fish apt repository
  ansible.builtin.apt_repository:
    repo: "deb http://download.opensuse.org/repositories/filesystems:/snapper/Debian_{{ ansible_distribution_major_version }}/ /"
    filename: filesystems_snapper.list
    state: present
    update_cache: false
- name: Install fish
  ansible.builtin.apt:
    name: fish
    update_cache: true
