---
- name: Install on Debian
  when: ansible_distribution == 'Debian'
  ansible.builtin.include_tasks:
    file: install_debian.yaml
- name: Install on Ubuntu
  when: ansible_distribution == 'Ubuntu'
  ansible.builtin.include_tasks:
    file: install_ubuntu.yaml
