---
- name: Install on Debian and Ubuntu
  when: ansible_facts['distribution'] in ['Debian', 'Ubuntu']
  block:
    - name: Configure the apt source
      ansible.builtin.include_tasks: apt_repo.yaml

    - name: Install snapper
      ansible.builtin.apt:
        name: snapper
        state: present
        update_cache: true
