[tools]
python = '3'

[env]
_.python.venv = { path = ".venv", create = true }

[settings.python]
uv_venv_auto = false

[tasks.bootstrap]
description = 'Bootstrap Ansible environment'
run = [
  'python -m ensurepip --upgrade',
  'python -m pip install -r requirements.txt',
  'ansible-galaxy install -r requirements.yaml'
]

[tasks.facts]
description = "Get facts for a host"
run = 'ansible --module-name ansible.builtin.setup {{arg(name="hostname")}}'
