---
- name: Configure ups-monitor-rack
  hosts: ups-monitor-rack
  become: true

  roles:
    # - configure_server
    - role: nut
      vars:
        nut_enable_server: true
        nut_enable_server_remote_access: true
        nut_upses:
          - name: "{{ ups_monitor_rack_nut_ups_name }}"
            driver: usbhid-ups # required
            port: auto # required
            desc: APC Smart-UPS SMT1500RM2U
            vendorid: "051D"
            productid: "0003"
        nut_monitor_primary_password: "{{ ups_monitor_rack_nut_upsmon_password }}"
        nut_monitor_secondary_users: >-
          {{
            [{'name': 'homeassistant', 'password': ups_monitor_rack_nut_homeassistant_password}]
            + [
              {'name': hostvars[h].nut_client_username, 'password': hostvars[h].nut_client_password}
              for h in groups['ups_monitor_rack_nut_clients']
            ]
          }}
        nut_notify_pushover_token: "{{ nut_pushover_token }}"
        nut_notify_pushover_user_key: "{{ pushover_user_key }}"
