---
- name: Configure ups-monitor-rack
  hosts: ups-monitor-rack
  become: true

  roles:
    - role: configure_server
    - role: nut
      vars:
        nut_enable_server: true
        nut_enable_server_remote_access: true
        nut_upses:
          - name: "{{ ups_monitor_rack_nut_ups_name }}"
            driver: usbhid-ups # required
            port: auto # required
            desc: APC Back-UPS RS1000G
            vendorid: "051D"
            productid: "0002"
        nut_monitor_primary_password: "{{ ups_monitor_rack_nut_upsmon_password }}"
        nut_monitor_secondary_users:
          - name: homeassistant
            password: "{{ ups_monitor_rack_nut_homeassistant_password }}"
          - name: "{{ ups_monitor_rack_nut_nas_host_01_username }}"
            password: "{{ ups_monitor_rack_nut_nas_host_01_password }}"
          - name: "{{ ups_monitor_rack_nut_vm_host_01_username }}"
            password: "{{ ups_monitor_rack_nut_vm_host_01_password }}"
        nut_notify_pushover_token: "{{ nut_pushover_token }}"
        nut_notify_pushover_user_key: "{{ pushover_user_key }}"
