---
- name: Configure Proxmox nas-host-01 host
  hosts: nas-host-01
  become: true

  roles:
  #   - pve_config
  #   - pve_cluster_acme
  #   - pve_node_acme
  #   - configure_server
  #   - pve_storage_add_nas_01_proxmox
  #   - scrutiny_collector
    - role: nut
      vars:
        nut_enable_client: true
        nut_client_servers:
          - ups_name: "{{ ups_monitor_rack_nut_ups_name }}"
            server_address: "{{ ups_monitor_rack_nut_server_address }}"
            username: "{{ ups_monitor_rack_nut_nas_host_01_username }}"
            password: "{{ ups_monitor_rack_nut_nas_host_01_password }}"

# Make sure the Proxmox VM video output is VGA
  tasks:
    - name: Configure network interfaces
      ansible.builtin.copy:
        src: files/nas-host-01/interfaces
        dest: /etc/network/interfaces
        mode: "0644"
        owner: root
        group: root
