---
- name: Configure jetson-01
  hosts: jetson-01
  become: true
  roles:
    # - configure_server
    # - geerlingguy.docker
    # - role: mise
    - role: docker_compose
      vars:
        docker_compose_src_file_path: files/jetson-01/docker-compose-home-assistant-wyoming.yml
        docker_compose_copy_scripts: true
