---
- name: Configure nas
  hosts: nas-01
  become: true

  tasks:
    - name: Add new snapraid-btrfs data disk
      vars:
        snapraid_btrfs_add_data_disk_dev: "/dev/disk/by-id/scsi-SATA_WDC_WD140EDFZ-11_X1GH3GLL"
      ansible.builtin.include_role:
        name: snapraid_btrfs_add_data_disk
