---
- name: Configure pi-turntable
  hosts: pi-turntable
  become: true

  roles:
    - role: prometheus.prometheus.node_exporter
    - role: docker_compose_traefik
      vars:
        docker_compose_traefik_enable_dashboard: true
        docker_compose_traefik_enable_host_network: true
    - role: docker_compose_dashboard_services_manager_provider
    - role: docker_compose_owntone
    - role: alsa_dsnoop
    - role: owntone_alsa_pipe
      vars:
        owntone_alsa_pipe_alsa_device: dsnoopusb
    - role: docker_compose_needledrop
      vars:
        docker_compose_needledrop_lastfm_enabled: true
        docker_compose_needledrop_lastfm_api_key: "{{ needledrop_lastfm_api_key }}"
        docker_compose_needledrop_lastfm_api_secret: "{{ needledrop_lastfm_api_secret }}"
        docker_compose_needledrop_lastfm_username: "{{ needledrop_lastfm_username }}"
        docker_compose_needledrop_lastfm_password_hash: "{{ needledrop_lastfm_password_hash }}"
        docker_compose_needledrop_tuneshine: "tuneshine.{{ domain_name }}"
