---
# No overrides are needed for API endpoints to be the tailnet versions
# because for the offsite group, domain_name = {{ tailscale_tailnet }}
# i.e.:
# - beszel.{{ domain_name }}
# - scrutiny.{{ domain_name }}

- name: Configure offsite-nas
  hosts: offsite-nas
  become: true

  vars:
    syncoid_destination_username: "{{ offsite_nas_syncoid_username }}"

  roles:
    - configure_server
    - artis3n.tailscale.machine
    - role: backup_destination
      vars:
        syncoid_source_ssh_public_keys:
          - "{{ nas_01_syncoid_ssh_public_key }}"
          - "{{ backup_01_syncoid_ssh_public_key }}"
        syncoid_destination_dataset: backups
        sanoid_src_conf_file_path: files/offsite-nas/sanoid.conf
        scrutiny_collector_systemd_requires: tailscaled.service sys-subsystem-net-devices-tailscale0.device
        scrutiny_collector_systemd_after: tailscaled.service sys-subsystem-net-devices-tailscale0.device
    - role: shutdown_tracker
      vars:
        shutdown_tracker_destination: true
        shutdown_tracker_expected_sources:
          - name: backup-01
            busy_check_command: "pgrep -fa 'zfs receive'"
          - name: nas-01
            busy_check_command: "pgrep -fa 'zfs receive'"
        shutdown_tracker_destination_username: "{{ syncoid_destination_username }}"
    - role: samba
      vars:
        samba_users:
          - username: "{{ offsite_nas_smb_username }}"
            password: "{{ offsite_nas_smb_password }}"
        samba_homes_enabled: false
        samba_shares:
          - name: offsite-homeassistant_backups
            path: /mnt/backups/offsite-homeassistant/backups
