---
- name: Configure Proxmox nas-host-01 host
  hosts: nas-host-01
  become: true

  roles:
    # - pve_config
    # - pve_cluster_acme
    # - pve_node_acme
    # - pve_storage_add_nas_01_proxmox
    # - pve_storage_add_backup_01_pbs
    # - geerlingguy.ntp
    # - configure_server
    # - scrutiny_collector
    - role: prometheus.prometheus.node_exporter
    # - role: power_saving
    #   vars:
    #     power_saving_pcie_runtime_devices:
    #       - vendor_id: "1022" # AMD
    #         device_id: "7901" # FCH SATA Controller
    #     power_saving_sata_all_devices: true
#     - role: nut
#       vars:
#         nut_enable_client: true
#         nut_client_servers:
#           - ups_name: "{{ ups_monitor_rack_nut_ups_name }}"
#             server_address: "{{ ups_monitor_rack_nut_server_address }}"
#             username: "{{ ups_monitor_rack_nut_nas_host_01_username }}"
#             password: "{{ ups_monitor_rack_nut_nas_host_01_password }}"
#     - role: pikvm_remote_command
#       vars:
#         pikvm_remote_command_ssh_public_key: "{{ pikvm_kvmd_ssh_public_key }}"
#     - role: remote_power_control
    # - role: pve_backup_job_script
    #   vars:
    #     pve_backup_job_script_job_init_commands:
    #       - /usr/local/bin/remote_power_control pikvm on
    #     pve_backup_job_script_healthchecks_io_uuid: f3d49b86-6d6b-410a-a252-299d84f43fd3

# # Make sure the Proxmox VM video output is VGA
  # tasks:
  # - name: Add contrib, non-free, and non-free-firmware repository
  #   ansible.builtin.replace:
  #     dest: /etc/apt/sources.list
  #     regexp: '^(deb.+main).*$'
  #     replace: '\1 contrib non-free non-free-firmware'
  # - name: Install packages
  #   ansible.builtin.apt:
  #     name:
  #       - amd-microcode
  #     update_cache: true
  #   - name: Configure network interfaces
  #     ansible.builtin.copy:
  #       src: files/nas-host-01/interfaces
  #       dest: /etc/network/interfaces
  #       mode: "0644"
  #       owner: root
  #       group: root
