---
- name: Configure Proxmox nas-host-02
  hosts: nas-host-02
  become: true

  roles:
  #   - pve_cluster_acme
  #   - pve_node_acme
  #   - pve_config
  #   - pve_storage_add_nas_01_proxmox
  #   - configure_server
  #   - scrutiny_collector
    - role: kernel_parameters
      vars:
        kernel_parameters_new_parameters:
          amd_pstate: active
          cpufreq.default_governor: powersave
          pcie_aspm.policy: powersave

  tasks:
    - name: Configure network interfaces
      ansible.builtin.copy:
        src: files/nas-host-02/interfaces
        dest: /etc/network/interfaces
        mode: "0644"
        owner: root
        group: root
    # - name: Add syncoid user
    #   ansible.builtin.user:
    #     name: "{{ nas_02_syncoid_username }}"
    #     password: '!'
    # - name: Authorize nas-01 syncoid key for syncoid user
    #   ansible.posix.authorized_key:
    #     user: "{{ nas_02_syncoid_username }}"
    #     state: present
    #     key: "{{ nas_01_syncoid_ssh_public_key }}"
    # - name: Allow syncoid user to shutdown
    #   ansible.builtin.lineinfile:
    #     path: /etc/sudoers
    #     line: "{{ nas_02_syncoid_username }} ALL=NOPASSWD: /usr/sbin/shutdown"
