---
- name: Configure pi-rack
  hosts: pi-rack
  become: true

  roles:
    - configure_server
    - role: nut
      vars:
        nut_enable_server: true
        nut_enable_server_remote_access: true
        nut_upses:
          - name: "{{ ups_monitor_rack_nut_ups_name }}"
            driver: usbhid-ups # required
            port: auto # required
            desc: APC Smart-UPS SMT1500RM2U
            vendorid: "051D"
            productid: "0003"
        nut_monitor_primary_password: "{{ ups_monitor_rack_nut_upsmon_password }}"
        nut_monitor_secondary_users:
          - name: homeassistant
            password: "{{ ups_monitor_rack_nut_homeassistant_password }}"
          - name: "{{ ups_monitor_rack_nut_nas_host_01_username }}"
            password: "{{ ups_monitor_rack_nut_nas_host_01_password }}"
          - name: "{{ ups_monitor_rack_nut_vm_host_01_username }}"
            password: "{{ ups_monitor_rack_nut_vm_host_01_password }}"
          # - name: "{{ ups_monitor_rack_nut_network_02_username }}"
          #   password: "{{ ups_monitor_rack_nut_network_02_password }}"
        nut_notify_pushover_token: "{{ nut_pushover_token }}"
        nut_notify_pushover_user_key: "{{ pushover_user_key }}"

  tasks:
    - name: Set POE+ HAT PWM fan values
      ansible.builtin.blockinfile:
        block: |
          dtparam=poe_fan_temp0=50000
          dtparam=poe_fan_temp1=60000
          dtparam=poe_fan_temp2=70000
          dtparam=poe_fan_temp3=80000
        path: /boot/firmware/config.txt
