- name: Configure first cluster node
  hosts: vm-host-01
  become: true

  roles:
    - pve_cluster_create
    - pve_cluster_ceph

- name: Configure other cluster nodes
  hosts:
    # - vm-host-02
    - nas-host-01
  become: true

  roles:
    # - pve_cluster_add_node
    - pve_node_ceph
