---
- name: Configure Proxmox nas-host-01 host
  hosts: nas-host-01
  become: true

  roles:
  #   - pve_config
  #   - pve_cluster_acme
  #   - pve_node_acme
  #   - configure_server
  #   - pve_storage_add_nas_01_proxmox
  #   - scrutiny_collector
    - role: kernel_parameters
      vars:
        kernel_parameters_new_parameters:
          video:
            - efifb:off
            - vesa:off
          amd_pstate: active
          cpufreq.default_governor: powersave
          pcie_aspm.policy: powersave

# Make sure the Proxmox VM video output is VGA
  tasks:
    - name: Configure network interfaces
      ansible.builtin.copy:
        src: files/nas-host-01/interfaces
        dest: /etc/network/interfaces
        mode: "0644"
        owner: root
        group: root
