---
- name: Configure docker-01
  hosts: docker-01
  become: true

  vars:
    docker_compose_dst_data_directory_path: "/mnt/data"

  roles:
    # - configure_server
    # - geerlingguy.docker
    - role: docker_compose_traefik
      vars:
        docker_compose_traefik_enable_dashboard: true
    - role: docker_compose_diun
    - role: docker_compose
      vars:
        docker_compose_copy_scripts: true
        docker_compose_src_file_path: files/docker-01/docker-compose-media.yml
        docker_compose_envs:
          JELLYSTAT_DB_USERNAME: "{{ jellystat_db_username }}"
          JELLYSTAT_DB_PASSWORD: "{{ jellystat_db_password }}"
          JELLYSTAT_JWT_SECRET: "{{ jellystat_jwt_secret }}"
    - role: docker_compose
      vars:
        docker_compose_copy_scripts: true
        docker_compose_src_file_path: files/docker-01/docker-compose-monitoring.yml
        docker_compose_envs:
          HEALTHCHECKS_EMAIL_HOST: "{{ smtp_host }}"
          HEALTHCHECKS_EMAIL_PORT: "{{ smtp_port }}"
          HEALTHCHECKS_EMAIL_HOST_USER: "{{ smtp_username }}"
          HEALTHCHECKS_EMAIL_HOST_PASSWORD: "{{ smtp_password }}"
          HEALTHCHECKS_EMAIL_USE_TLS: "True"
          HEALTHCHECKS_SUPERUSER_EMAIL: "{{ healthchecks_superuser_email }}"
          HEALTHCHECKS_SUPERUSER_PASSWORD: "{{ healthchecks_superuser_password }}"
          HEALTHCHECKS_PUSHOVER_API_TOKEN: "{{ healthchecks_pushover_token }}"
          HEALTHCHECKS_PUSHOVER_SUBSCRIPTION_URL: "{{ healthchecks_pushover_subscription_url }}"
    - role: docker_compose
      vars:
        docker_compose_copy_scripts: true
        docker_compose_src_file_path: files/docker-01/docker-compose-utilities.yml
  tasks:
    - name: Install packages
      ansible.builtin.package:
        name:
          - zfsutils-linux
