---
- name: Configure nas
  hosts: media-01
  become: true

  vars:
    docker_compose_dst_data_directory_path: /mnt/data

  roles:
    - configure_server
    - geerlingguy.docker
    - role: nvidia.nvidia_driver
      vars:
        nvidia_driver_skip_reboot: true
        nvidia_driver_branch: "535"
        nvidia_driver_ubuntu_install_from_cuda_repo: true
        nvidia_driver_add_repos: false
    - nvidia.nvidia_docker
    - role: power_saving
      vars:
        power_saving_configure_cpu: false
        power_saving_pci_runtime_devices:
          # Nvidia T600 Video
          - vendor_id: "0x10de"
            device_id: "0x1fb1"
          # Nvidia T600 Audio
          - vendor_id: "0x10de"
            device_id: "0x10fa"
    - role: docker_compose_traefik
      vars:
        docker_compose_traefik_enable_dashboard: true
        docker_compose_traefik_enable_host_network: true
    - docker_compose_dashboard_services_manager_provider
    - docker_compose_diun
    - role: docker_compose_immich
      vars:
        immich_only_machine_learning: true
        immich_machine_learning_cuda: true
        immich_machine_learning_model_cache_directory: "{{ (docker_compose_dst_data_directory_path, 'immich/model_cache') | path_join }}"
    - role: docker_compose
      vars:
        docker_compose_copy_scripts: true
        docker_compose_src_file_path: files/media-01/docker-compose-media-01.yml
        docker_compose_envs:
          PLEX_CLAIM_TOKEN: "{{ plex_claim_token }}"
          SMB_STORAGE_USERNAME: "{{ smb_nas_01_username }}"
          SMB_STORAGE_PASSWORD: "{{ smb_nas_01_password }}"
          SMB_STORAGE_UID: "{{ smb_nas_01_uid }}"
          SMB_STORAGE_GID: "{{ smb_nas_01_gid }}"
