---
- name: Install samba
  ansible.builtin.package:
    name: samba
# https://stackoverflow.com/a/71050848
- name: Create samba users
  ansible.builtin.shell: >
    set -e -o pipefail
    && (pdbedit --user={{ samba_users_item.username }} 2>&1 > /dev/null)
    || (echo '{{ samba_users_item.password }}'; echo '{{ samba_users_item.password }}')
    | smbpasswd -s -a {{ samba_users_item.username }}
  args:
    executable: /bin/bash
  register: samba_create_users
  changed_when: "'Added user' in samba_create_users.stdout"
  loop: "{{ samba_users }}"
  loop_control:
    loop_var: samba_users_item
  no_log: true
- name: Configure samba
  ansible.builtin.template:
    src: "templates/smb.conf.j2"
    dest: "/etc/samba/smb.conf"
    owner: root
    group: root
    mode: '0644'
  register: copy_smb_conf_result
- name: Restart smbd # noqa no-handler
  when: copy_smb_conf_result.changed
  ansible.builtin.systemd:
    name: smbd
    state: restarted
