---
- name: Add nvidia apt repository key
  ansible.builtin.get_url:
    url: "https://nvidia.github.io/libnvidia-container/gpgkey"
    dest: "{{ nvidia_container_toolkit_keyring_path }}"
    mode: '0644'
    force: true
# - name: Get latest release from GitHub
#   ansible.builtin.uri:
#     url: "{{ nvidia_container_toolkit_apt_sources_list_url }}"
#     return_content: true
#   register:
#     nvidia_container_toolkit_apt_sources_list_result
- name: Add nvidia apt repository
  ansible.builtin.copy:
    content: |
      deb [signed-by={{ nvidia_container_toolkit_keyring_path }}] https://nvidia.github.io/libnvidia-container/stable/deb/$(ARCH) /
      deb [signed-by={{ nvidia_container_toolkit_keyring_path }}] https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/$(ARCH) /
      #deb [signed-by={{ nvidia_container_toolkit_keyring_path }}] https://nvidia.github.io/libnvidia-container/experimental/deb/$(ARCH) /
      #deb [signed-by={{ nvidia_container_toolkit_keyring_path }}] https://nvidia.github.io/libnvidia-container/experimental/ubuntu18.04/$(ARCH) /
    dest: /etc/apt/sources.list.d/nvidia-container-toolkit.list
    mode: "0644"
- name: Install nvidia-container-toolkit
  ansible.builtin.apt:
    name: nvidia-container-toolkit
    update_cache: true
- name: Add nvidia runtime to docker
  ansible.builtin.command:
    cmd: nvidia-ctk runtime configure --runtime=docker
  changed_when: false
- name: Restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
