---
- name: Copy Github SSH authorized keys
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    key: https://github.com/andyattebery.keys
    state: present

- name: Add SSH authorized keys
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ ssh_public_key }}"
    state: present
  loop:
    - "{{ blink_ssh_public_key }}"
    - "{{ ideapad_3_ssh_public_key }}"
    - "{{ servercat_ssh_public_key }}"
    - "{{ steamdeck_ssh_public_key }}"
  loop_control:
    loop_var: ssh_public_key

- name: Enable SSH forwarding for sudo
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    insertafter: '^#?\s*Defaults\s+env_keep\b'
    line: 'Defaults    env_keep += "SSH_AUTH_SOCK"'

- name: Set timezone
  community.general.timezone:
    name: "{{ timezone }}"

- name: Run roles
  ansible.builtin.include_role:
    name: "{{ role_item }}"
  loop:
    - geerlingguy.security
    - fish_install
    - configure_dotfiles
  loop_control:
    loop_var: role_item
  vars:
    security_fail2ban_enabled: false
    security_autoupdate_enabled: false
    fish_install_change_shell: true
