---
- name: Check for rpm-ostree
  ansible.builtin.command:
    cmd: which rpm-ostree
  register: __configure_server_rpm_ostree_check
  changed_when: false
  failed_when: false

- name: Configure Fedora Atomic
  when: __configure_server_rpm_ostree_check.rc == 0
  ansible.builtin.include_tasks:
    file: fedora_immutable.yaml

- name: Configure standard server
  when: __configure_server_rpm_ostree_check.rc != 0
  ansible.builtin.include_tasks:
    file: standard.yaml
