---
- name: List ACME accounts
  ansible.builtin.uri:
    url: "{{ pbs_api_base_url }}/config/acme/account"
    method: GET
    headers: "{{ pbs_api_headers }}"
    validate_certs: false
    return_content: true
  register: pbs_acme_account_list

- name: Register default ACME account
  when:
    - (pbs_acme_account_list.content | from_json).data
      | selectattr('name', 'equalto', 'default')
      | list | length == 0
  block:
    - name: Get ACME TOS URL
      ansible.builtin.uri:
        url: "{{ pbs_api_base_url }}/config/acme/tos"
        method: GET
        headers: "{{ pbs_api_headers }}"
        validate_certs: false
        return_content: true
      register: pbs_acme_tos_result

    - name: Register ACME account
      ansible.builtin.uri:
        url: "{{ pbs_api_base_url }}/config/acme/account"
        method: POST
        headers: "{{ pbs_api_headers }}"
        validate_certs: false
        body_format: form-urlencoded
        body:
          name: default
          contact: "{{ pve_acme_contact_email }}"
          directory: https://acme-v02.api.letsencrypt.org/directory
          tos_url: "{{ (pbs_acme_tos_result.content | from_json).data }}"
        status_code: [200]

- name: List ACME plugins
  ansible.builtin.uri:
    url: "{{ pbs_api_base_url }}/config/acme/plugins"
    method: GET
    headers: "{{ pbs_api_headers }}"
    validate_certs: false
    return_content: true
  register: pbs_acme_plugin_list

- name: Add CloudFlare ACME DNS plugin
  when:
    - (pbs_acme_plugin_list.content | from_json).data
      | selectattr('api', 'defined')
      | selectattr('api', 'equalto', 'cf')
      | list | length == 0
  vars:
    acme_plugin_cloudflare_config: |-
      CF_Account_ID={{ cloudflare_account_id }}
      CF_Token={{ cloudflare_api_token }}
  ansible.builtin.uri:
    url: "{{ pbs_api_base_url }}/config/acme/plugins"
    method: POST
    headers: "{{ pbs_api_headers }}"
    validate_certs: false
    body_format: form-urlencoded
    body:
      id: cloudflare
      type: dns
      api: cf
      data: "{{ acme_plugin_cloudflare_config | b64encode }}"
    status_code: [200]
