---
# - name: Get node config
#   ansible.builtin.command:
#     cmd: "{{ pbs_curl_base_get_command }}/nodes/{{ ansible_hostname }}/config"
#   register: pbs_curl_get_node_config_result
#   changed_when: false
# - ansible.builtin.debug:
#     msg: "{{ pbs_curl_get_node_config_result.stdout | from_json | json_query('acmedomain0') }}"
- name: Add ACME domain to node
  # when: "pbs_curl_get_node_config_result.stdout | from_json | json_query('acmedomain0') == ''"
  vars:
    node_fqdn: "{{ ansible_hostname }}.{{ domain_name }}"
  ansible.builtin.command:
    cmd: >
      {{ pbs_curl_base_put_command }}/nodes/{{ ansible_hostname }}/config
      --data acmedomain0='domain={{ node_fqdn }},plugin=cloudflare'
  register: pbs_curl_put_node_config_result
  changed_when: true
# - ansible.builtin.debug:
#     msg: "{{ pbs_curl_put_node_config_result.stdout }}"
- name: Get certificates info for node
  ansible.builtin.command:
    cmd: "{{ pbs_curl_base_get_command }}/nodes/{{ ansible_hostname }}/certificates/info"
  register: pbs_curl_get_node_certificates_info_result
  changed_when: false
# - ansible.builtin.debug:
#     msg: "{{ pbs_curl_get_node_certificates_info_result.stdout }}"
- name: Order ACME certificate for node
  vars:
    lets_encrypt_search_string: "\"issuer\": \"/C=US/O=Let's Encrypt/CN=R3\""
  when: "'s Encrypt,' not in pbs_curl_get_node_certificates_info_result.stdout"
  ansible.builtin.command:
    cmd: "{{ pbs_curl_base_post_command }}/nodes/{{ ansible_hostname }}/certificates/acme/certificate"
  register: pbs_curl_post_certificate_acme_certificate_result
  changed_when: true
