version: "3.8"

x-immich-server: &base-immich-server
  image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION}
  environment:
    - TZ=${TZ}
    - DB_DATABASE_NAME=${IMMICH_DB_DATABASE_NAME}
    - DB_HOSTNAME=immich-postgres
    - DB_PASSWORD=${IMMICH_DB_PASSWORD}
    - DB_USERNAME=${IMMICH_DB_USERNAME}
    - REDIS_HOSTNAME=immich-redis
  volumes:
    - ${IMMICH_PHOTOS_DIRECTORY}:/usr/src/app/upload
    - /etc/localtime:/etc/localtime:ro
  depends_on:
    - immich-redis
    - immich-database
  restart: unless-stopped

services:

  immich-server:
    <<: *base-immich-server
    container_name: immich-server
    command: [ "start.sh", "immich" ]
    networks:
      - traefik
      - immich
    labels:
      - traefik.enable=true
      - traefik.http.routers.immich.rule=Host(`immich.$DOMAIN_NAME`)
      - traefik.http.routers.immich.entrypoints=websecure
      - traefik.http.routers.immich.tls.certresolver=cloudflare
      - traefik.http.services.immich.loadbalancer.server.port=3001
      - dsm.name=Immich

  immich-microservices:
    <<: *base-immich-server
    container_name: immich-microservices
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    networks:
      - immich

  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION}
    volumes:
      - ${IMMICH_MACHINE_LEARNING_MODEL_CACHE_DIRECTORY}:/cache
    restart: unless-stopped
    networks:
      - immich

  immich-redis:
    container_name: immich-redis
    image: redis:6.2-alpine
    restart: unless-stopped
    networks:
      - immich

  immich-database:
    container_name: immich-postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    environment:
      POSTGRES_PASSWORD: ${IMMICH_DB_PASSWORD}
      POSTGRES_USER: ${IMMICH_DB_USERNAME}
      POSTGRES_DB: ${IMMICH_DB_DATABASE_NAME}
    volumes:
      - ${IMMICH_DB_DIRECTORY}:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - immich

networks:
  immich:
    name: immich
  traefik:
    name: traefik
    external: true