---
services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    restart: always
    command:
      # - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --metrics.prometheus=true
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entrypoints.websecure.address=:443
      - --log=true
      - --log.level=ERROR
      - --log.filePath=/logs/traefik.log
      # - --accessLog=true
      # - --accessLog.filePath=/logs/access.log
      # - --accessLog.bufferingSize=100
      - --certificatesresolvers.cloudflare.acme.dnschallenge=true
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cloudflare.acme.email=${CERTBOT_EMAIL}
      - --certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json
    networks:
      traefik:
    # extra_hosts:
    #   - host.docker.internal:172.17.0.1 # This is to make host network_mode containers work
    ports:
      - "80:80"
      - "443:443"
    environment:
      - "CF_DNS_API_TOKEN=${CLOUDFLARE_API_TOKEN}"
    volumes:
      - "${DOCKER_DATA_DIRECTORY}/traefik/letsencrypt:/letsencrypt"
      - "${DOCKER_DATA_DIRECTORY}/traefik/logs:/logs"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    # labels:
    #   - traefik.enable=true
    #   - "traefik.http.routers.dashboard-https.rule=Host(`traefik.$HOSTNAME.$DOMAIN_NAME`)"
    #   - traefik.http.routers.dashboard-https.entrypoints=websecure
    #   - traefik.http.routers.dashboard-https.tls.certresolver=cloudflare
    #   - traefik.http.routers.dashboard-https.service=api@internal
networks:
  traefik:
    name: traefik
